### ISSUE TITLE
R and B flipped?

### ISSUE THREAD

**Issue by DennisWelu** [sidorares/node-vnc#2]
Hi Andrey, looking at this example of drawing to the 2d context: https://github.com/sidorares/node-vnc/blob/master/vnc.js#L43-L55

I've found if I pass the rect along to a browser client and render it there the Red and Blue channels are flipped so the colors are not right. I'll refer to another example of yours where you are capturing the updates in a local Buffer and flipping 0 and 2 indexes: https://github.com/sidorares/rfbrecord/blob/master/rfbrec.js#L59-L61.

If I flip the 0 and 2 index in the rect.data the colors render correctly.

**Comment by sidorares** [comment]
it can be actually in any order/size, you need to process bpp, red_shift + red_mask values ( + G and B ) - see https://github.com/sidorares/node-rfb2/blob/7f97d65ec17454d7b4c435f5128be68d7df849f3/rfbclient.js#L176-L185

Unfortunately I don't have ( yet ) code to do this conversion for you, I'd like to allow rfb2 client users to just tell "please do conversion for me when you receive data and return rgb24 regardless on the format server sends to you"

**Comment by sidorares** [comment]
See some example code here https://gist.github.com/iam-peekay/990c43e7e7617f30809b - values are hard-coded for bgr565 format ( 16 bits bpp, 5bit red, 6bit green, 5 bit blue )

**Comment by DennisWelu** [comment]
Ah! Did not realize the possibility of variability. If I know I'm always working with a certain server type and configuration that makes it easier I suppose - in my case that is the situation. So I can just do what I'm doing (flip the 0 and 2) without the fancy math. Until a nice feature like you mention is added to do it within rfb2. Thanks for the info and pointers to reference/example code!
